apiVersion: apps/v1
kind: Deployment
metadata:
  name: bayesian-diagnosis-api
  labels:
    app: bayesian-diagnosis-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bayesian-diagnosis-api
  template:
    metadata:
      labels:
        app: bayesian-diagnosis-api
    spec:
      containers:
      - name: api
        image: bayesian-diagnosis-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi" 
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: dataset-volume
          mountPath: /app/clinical_signs_and_symptoms_in_rare_diseases.csv
          subPath: clinical_signs_and_symptoms_in_rare_diseases.csv
          readOnly: true
      volumes:
      - name: dataset-volume
        configMap:
          name: dataset-config

---
apiVersion: v1
kind: Service
metadata:
  name: bayesian-diagnosis-service
spec:
  selector:
    app: bayesian-diagnosis-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset-config
data:
  clinical_signs_and_symptoms_in_rare_diseases.csv: |
    # Your CSV data goes here
    # This should be replaced with actual data