[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements_railway.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python3 start.py"