[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PYTHONUNBUFFERED = "1"

# Note: Set these in Railway dashboard:
# SUPABASE_URL = "your_supabase_url"
# SUPABASE_ANON_KEY = "your_supabase_anon_key"
# SUPABASE_SERVICE_KEY = "your_service_key"