[build]
builder = "nixpacks"

[deploy]
startCommand = "python main_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"

# Note: Set these in Railway dashboard:
# SUPABASE_URL = "your_supabase_url"
# SUPABASE_ANON_KEY = "your_supabase_anon_key"